language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.2.1.gemfile
  - gemfiles/rails_6.0.0.gemfile
  - gemfiles/rails_master.gemfile
matrix:
  allow_failures:
    - gemfile: 'gemfiles/rails_master.gemfile'
    - gemfile: gemfiles/rails_6.0.0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/rails_6.0.0.gemfile
      rvm: 2.4.7
before_install: gem install bundler -v '~> 2.0'
