# Step 1: Frontend Build
FROM node:18-alpine AS build

ARG ENVIRONMENT_FILE=".env.production"

WORKDIR /app

COPY frontend/${ENVIRONMENT_FILE} .env
COPY frontend/package*.json ./

RUN npm install

COPY frontend/. .

RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build /app/build /usr/share/nginx/html
COPY ./proxy/nginx.frontends.conf /etc/nginx/conf.d/default.conf

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
