FROM ruby:3.2.2-bullseye AS rails-builder

ENV appuser=rails
ENV RAILS_ENV=production

# TODO: make env vars nilable with reasonable defaults
ENV DEFAULT_FROM_EMAIL_ADDRESS="noreply@icfc.net"
ENV SMTP_HOST=dummy.host
ENV SMTP_USERNAME=dummy
ENV SMTP_PASSWORD=dummy
ENV RECAPTCHA_SECRET_KEY=123456
ENV DOMAIN=icfc.net
ENV AWS_ACCESS_KEY_ID=123
ENV AWS_SECRET_ACCESS_KEY=123
ENV AWS_S3_REGION=us-east-1
ENV AWS_BUCKET=hello-world

WORKDIR /rails

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

COPY api/Gemfile api/Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY api/. .
COPY api/entrypoint.sh /rails/entrypoint.sh
RUN chmod +x /rails/entrypoint.sh

RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile

RUN adduser --disabled-password --gecos "" ${appuser}
RUN chown -R ${appuser}:${appuser} /rails
RUN chmod 755 /rails

USER ${appuser}

ENTRYPOINT ["/rails/entrypoint.sh"]
