services:
  proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    depends_on:
      - frontend
      - api
    networks:
      - icfc
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: "npm run dev"
    ports:
      - 5173:5173
    env_file:
      - ".env"
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app
    networks:
      - icfc
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["rails", "server", "--binding=0.0.0.0"]
    env_file:
      - ".env"
    depends_on:
      - postgres
    ports:
      - "3010:3000"
    volumes:
      - gems:/usr/local/bundle
      - ./api:/app
    networks:
      - icfc
  postgres:
    image: postgres:12-alpine
    ports:
      - "8881:5432"
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - icfc

volumes:
  gems:
  postgres-data:
  frontend-node-modules:

networks:
  icfc: