services:
  proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    depends_on:
      - frontend
      - api
    networks:
      - icfc
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: "npm run dev"
    ports:
      - 5173:5173
    env_file:
      - ".env"
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app
    networks:
      - icfc
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["rails", "server", "--binding=0.0.0.0"]
    env_file:
      - ".env"
    depends_on:
      - postgres
    ports:
      - "3010:3000"
    volumes:
      - gems:/usr/local/bundle
      - ./api:/app
    networks:
      - icfc
  postgres:
    image: postgres:12-alpine
    ports:
      - "8881:5432"
    env_file:
      - ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - icfc
  prometheus:
    image: prom/prometheus:v2.53.3
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    env_file:
      - ".env"
    ports:
      - "9090:9090"
    networks:
      - icfc
  grafana:
    image: grafana/grafana:10.4.12
    ports:
      - "3001:3000"
    env_file:
      - ".env"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - icfc
  alertmanager:
    image: prom/alertmanager:v0.27.0
    env_file:
      - ".env"
    ports:
      - "9093:9093"
    networks:
      - icfc

volumes:
  gems:
  postgres-data:
  frontend-node-modules:
  grafana-storage:

networks:
  icfc:

x-mutagen:
  sync:
    gems:
      alpha: "./api"
      beta: "volume://gems"
      mode: "two-way-safe"
    frontend-node-modules:
      alpha: "./frontend"
      beta: "volume://frontend-node-modules"
      mode: "two-way-safe"