services:
  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - production_api
    networks:
      - deployed_network
  production_api:
    image: ghcr.io/diehlms/icfc-api:latest
    restart: always
    entrypoint: ["/bin/bash", "/rails/entrypoint.sh"]
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    env_file:
      - .env.production
    volumes:
      - ./entrypoint.sh:/rails/entrypoint.sh
    networks:
      - deployed_network
  productionpostgres: # no underscores allowed
    image: postgres:16-bullseye
    restart: always
    ports:
      - 8881:5432
    env_file:
      - .env.production
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - deployed_network
volumes:
  postgres-data-production:
  caddy_data:
  caddy_config:
networks:
  deployed_network:
    driver: bridge