name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0"]
        gemfile:
          - rails_5_2
          - rails_6_0
          - rails_6_1
          - rails_7
        exclude:
          - ruby: "3.0"
            gemfile: "rails_5_2"
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
