# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `carrierwave-aws` gem.
# Please instead update this file by running `bin/tapioca gem carrierwave-aws`.


# source://carrierwave-aws//lib/carrierwave/storage/aws.rb#5
module CarrierWave; end

# source://carrierwave-aws//lib/carrierwave/storage/aws.rb#6
module CarrierWave::Storage; end

# source://carrierwave-aws//lib/carrierwave/storage/aws.rb#7
class CarrierWave::Storage::AWS < ::CarrierWave::Storage::Abstract
  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#26
  def cache!(file); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#40
  def clean_cache!(_seconds); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#44
  def connection; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#52
  def credentials; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#36
  def delete_dir!(path); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#22
  def retrieve!(identifier); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#32
  def retrieve_from_cache!(identifier); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#16
  def store!(file); end

  class << self
    # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#12
    def clear_connection_cache!; end

    # source://carrierwave-aws//lib/carrierwave/storage/aws.rb#8
    def connection_cache; end
  end
end

# source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#7
class CarrierWave::Storage::AWSFile
  # @return [AWSFile] a new instance of AWSFile
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#13
  def initialize(uploader, connection, path); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#32
  def attributes; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#88
  def authenticated_url(options = T.unsafe(nil)); end

  # Returns the value of attribute aws_options.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def aws_options; end

  # Sets the attribute aws_options
  #
  # @param value the value to set the attribute aws_options to.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def aws_options=(_arg0); end

  # Returns the value of attribute connection.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def connection; end

  # Sets the attribute connection
  #
  # @param value the value to set the attribute connection to.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def connection=(_arg0); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#11
  def content_type(*_arg0, **_arg1, &_arg2); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#70
  def copy_to(new_path); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#11
  def delete(*_arg0, **_arg1, &_arg2); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#11
  def exists?(*_arg0, **_arg1, &_arg2); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#36
  def extension; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#20
  def file; end

  # Sets the attribute file
  #
  # @param value the value to set the attribute file to.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#8
  def file=(_arg0); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#41
  def filename(options = T.unsafe(nil)); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#77
  def move_to(new_path); end

  # Returns the value of attribute path.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def path; end

  # Sets the attribute path
  #
  # @param value the value to set the attribute path to.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def path=(_arg0); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#96
  def public_url; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#47
  def read; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#84
  def signed_url(options = T.unsafe(nil)); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#24
  def size; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#57
  def store(new_file); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#30
  def to_file; end

  # Returns the value of attribute uploader.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def uploader; end

  # Sets the attribute uploader
  #
  # @param value the value to set the attribute uploader to.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#9
  def uploader=(_arg0); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#104
  def url(options = T.unsafe(nil)); end

  private

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#132
  def asset_host; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#116
  def bucket; end

  # @return [Boolean]
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#128
  def public?; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#120
  def signer; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_file.rb#124
  def uri_path; end
end

# source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#5
class CarrierWave::Storage::AWSOptions
  # @return [AWSOptions] a new instance of AWSOptions
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#13
  def initialize(uploader); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#35
  def copy_options(file); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#37
  def expiration_options(options = T.unsafe(nil)); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#29
  def move_options(file); end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#17
  def read_options; end

  # Returns the value of attribute uploader.
  #
  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#11
  def uploader; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#21
  def write_options(new_file); end

  private

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#45
  def aws_attributes; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#52
  def aws_read_options; end

  # source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#56
  def aws_write_options; end
end

# source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#6
CarrierWave::Storage::AWSOptions::MULTIPART_THRESHOLD = T.let(T.unsafe(nil), Integer)

# Backward compatibility
#
# source://carrierwave-aws//lib/carrierwave/storage/aws_options.rb#9
CarrierWave::Storage::AWSOptions::MULTIPART_TRESHOLD = T.let(T.unsafe(nil), Integer)

# source://carrierwave-aws//lib/carrierwave/support/uri_filename.rb#4
module CarrierWave::Support; end

# source://carrierwave-aws//lib/carrierwave/support/uri_filename.rb#5
module CarrierWave::Support::UriFilename
  class << self
    # source://carrierwave-aws//lib/carrierwave/support/uri_filename.rb#6
    def filename(url); end
  end
end

# source://carrierwave-aws//lib/carrierwave-aws.rb#11
module CarrierWave::Uploader; end

# source://carrierwave-aws//lib/carrierwave-aws.rb#12
class CarrierWave::Uploader::Base
  include ::CarrierWave::Utilities::Uri

  # source://carrierwave-aws//lib/carrierwave-aws.rb#32
  def asset_host_public; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#32
  def asset_host_public=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#30
  def aws_acl; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#30
  def aws_acl=(acl); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#24
  def aws_attributes; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#24
  def aws_attributes=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#25
  def aws_authenticated_url_expiration; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#25
  def aws_authenticated_url_expiration=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#27
  def aws_bucket; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#27
  def aws_bucket=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#26
  def aws_credentials; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#26
  def aws_credentials=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#28
  def aws_read_options; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#28
  def aws_read_options=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#31
  def aws_signer; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#31
  def aws_signer=(value); end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#29
  def aws_write_options; end

  # source://carrierwave-aws//lib/carrierwave-aws.rb#29
  def aws_write_options=(value); end

  class << self
    # source://carrierwave-aws//lib/carrierwave-aws.rb#32
    def asset_host_public(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#32
    def asset_host_public=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#30
    def aws_acl(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#30
    def aws_acl=(acl); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#24
    def aws_attributes(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#24
    def aws_attributes=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#25
    def aws_authenticated_url_expiration(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#25
    def aws_authenticated_url_expiration=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#27
    def aws_bucket(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#27
    def aws_bucket=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#26
    def aws_credentials(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#26
    def aws_credentials=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#28
    def aws_read_options(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#28
    def aws_read_options=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#31
    def aws_signer(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#31
    def aws_signer=(signer); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#29
    def aws_write_options(value = T.unsafe(nil)); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#29
    def aws_write_options=(value); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#42
    def normalized_acl(acl); end

    # source://carrierwave-aws//lib/carrierwave-aws.rb#68
    def validated_signer(signer); end
  end
end

# source://carrierwave-aws//lib/carrierwave-aws.rb#13
CarrierWave::Uploader::Base::ACCEPTED_ACL = T.let(T.unsafe(nil), Array)

# source://carrierwave-aws//lib/carrierwave-aws.rb#22
class CarrierWave::Uploader::Base::ConfigurationError < ::StandardError; end

# source://carrierwave-aws//lib/carrierwave/aws/version.rb#3
module Carrierwave; end

# source://carrierwave-aws//lib/carrierwave/aws/version.rb#4
module Carrierwave::AWS; end

# source://carrierwave-aws//lib/carrierwave/aws/version.rb#5
Carrierwave::AWS::VERSION = T.let(T.unsafe(nil), String)
