# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fog-json` gem.
# Please instead update this file by running `bin/tapioca gem fog-json`.


# source://fog-json//lib/fog/json/version.rb#1
module Fog; end

# The {JSON} module includes functionality that is common between APIs using JSON to send and
# receive data.
#
# The intent is to provide common code for provider APIs using JSON but not require it for those
# using XML.
#
# source://fog-json//lib/fog/json.rb#12
module Fog::JSON
  class << self
    # source://fog-json//lib/fog/json.rb#39
    def decode(obj); end

    # Do the MultiJson introspection at this level so we can define our encode/decode methods and
    # perform the introspection only once rather than once per call.
    #
    # source://fog-json//lib/fog/json.rb#33
    def encode(obj); end

    # This cleans up Time objects to be ISO8601 format
    #
    # source://fog-json//lib/fog/json.rb#18
    def sanitize(data); end
  end
end

# source://fog-json//lib/fog/json.rb#14
class Fog::JSON::DecodeError < ::Fog::Errors::Error; end

# source://fog-json//lib/fog/json.rb#13
class Fog::JSON::EncodeError < ::Fog::Errors::Error; end

# source://fog-json//lib/fog/json/version.rb#2
module Fog::Json; end

# source://fog-json//lib/fog/json/version.rb#3
Fog::Json::VERSION = T.let(T.unsafe(nil), String)
