# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fog-xml` gem.
# Please instead update this file by running `bin/tapioca gem fog-xml`.


# source://fog-xml//lib/fog/xml/version.rb#1
module Fog; end

# source://fog-xml//lib/fog/xml.rb#14
module Fog::Parsers; end

# source://fog-xml//lib/fog/parsers/base.rb#5
class Fog::Parsers::Base < ::Nokogiri::XML::SAX::Document
  # @return [Base] a new instance of Base
  #
  # source://fog-xml//lib/fog/parsers/base.rb#8
  def initialize; end

  # source://fog-xml//lib/fog/parsers/base.rb#12
  def attr_value(name, attrs); end

  # source://fog-xml//lib/fog/parsers/base.rb#20
  def characters(string); end

  # source://fog-xml//lib/fog/parsers/base.rb#32
  def end_element_namespace(name, prefix = T.unsafe(nil), uri = T.unsafe(nil)); end

  # source://fog-xml//lib/fog/parsers/base.rb#16
  def reset; end

  # Returns the value of attribute response.
  #
  # source://fog-xml//lib/fog/parsers/base.rb#6
  def response; end

  # ###############################################################################
  #
  # source://fog-xml//lib/fog/parsers/base.rb#38
  def start_element(name, attrs = T.unsafe(nil)); end

  # ###############################################################################
  # This is a workaround. Original implementation from Nokogiri is overwritten with
  # one that does not join namespace prefix with local name.
  #
  # source://fog-xml//lib/fog/parsers/base.rb#28
  def start_element_namespace(name, attrs = T.unsafe(nil), prefix = T.unsafe(nil), uri = T.unsafe(nil), ns = T.unsafe(nil)); end

  # source://fog-xml//lib/fog/parsers/base.rb#42
  def value; end
end

# source://fog-xml//lib/fog/to_hash_document.rb#2
class Fog::ToHashDocument < ::Nokogiri::XML::SAX::Document
  # @return [ToHashDocument] a new instance of ToHashDocument
  #
  # source://fog-xml//lib/fog/to_hash_document.rb#3
  def initialize; end

  # source://fog-xml//lib/fog/to_hash_document.rb#26
  def body; end

  # source://fog-xml//lib/fog/to_hash_document.rb#7
  def characters(string); end

  # source://fog-xml//lib/fog/to_hash_document.rb#12
  def end_element(name); end

  # source://fog-xml//lib/fog/to_hash_document.rb#30
  def response; end

  # source://fog-xml//lib/fog/to_hash_document.rb#34
  def start_element(name, attributes = T.unsafe(nil)); end
end

# source://fog-xml//lib/fog/xml.rb#8
module Fog::XML; end

# source://fog-xml//lib/fog/xml/connection.rb#3
class Fog::XML::Connection < ::Fog::XML::SAXParserConnection
  # source://fog-xml//lib/fog/xml/connection.rb#4
  def request(params, &_block); end
end

# source://fog-xml//lib/fog/xml/response.rb#3
class Fog::XML::Response
  # @return [Response] a new instance of Response
  #
  # source://fog-xml//lib/fog/xml/response.rb#4
  def initialize(parser); end

  # source://fog-xml//lib/fog/xml/response.rb#10
  def call(chunk, _remaining, _total); end

  # source://fog-xml//lib/fog/xml/response.rb#20
  def finish; end

  # source://fog-xml//lib/fog/xml/response.rb#15
  def rewind; end
end

# source://fog-xml//lib/fog/xml/sax_parser_connection.rb#3
class Fog::XML::SAXParserConnection < ::Fog::Core::Connection
  # Makes a request using the connection using Excon
  #
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash]
  # @raise [Excon::Errors::StubNotFound]
  # @raise [Excon::Errors::Timeout]
  # @raise [Excon::Errors::SocketError]
  # @return [Excon::Response]
  #
  # source://fog-xml//lib/fog/xml/sax_parser_connection.rb#23
  def request(parser, params); end
end

# source://fog-xml//lib/fog/xml/version.rb#2
module Fog::Xml; end

# source://fog-xml//lib/fog/xml/version.rb#3
Fog::Xml::VERSION = T.let(T.unsafe(nil), String)
