# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fog-core` gem.
# Please instead update this file by running `bin/tapioca gem fog-core`.


# Format related hackery
# allows both true.is_a?(Fog::Boolean) and false.is_a?(Fog::Boolean)
# allows both nil.is_a?(Fog::Nullable::String) and ''.is_a?(Fog::Nullable::String)
#
# source://fog-core//lib/fog/core/version.rb#3
module Fog
  class << self
    # This is the named credential from amongst the configuration file being used or +:default+
    #
    # @note This can be set using the +FOG_CREDENTIAL+ environment variable
    # @return [Symbol] The credential to use in Fog
    #
    # source://fog-core//lib/fog/core/credentials.rb#40
    def credential; end

    # Assign a new credential to use from configuration file
    #
    # @param new_credential [String, Symbol] name of new credential to use
    # @return [Symbol] name of the new credential
    #
    # source://fog-core//lib/fog/core/credentials.rb#30
    def credential=(new_credential); end

    # @raise [LoadError] Configuration unavailable in configuration file
    # @return [Hash] The credentials pulled from the configuration file
    #
    # source://fog-core//lib/fog/core/credentials.rb#67
    def credentials; end

    # Sets the attribute credentials
    #
    # @param value the value to set the attribute credentials to.
    #
    # source://fog-core//lib/fog/core/credentials.rb#23
    def credentials=(_arg0); end

    # This returns the path to the configuration file being used globally to look for sets of
    # credentials
    #
    # @note This can be set using the +FOG_RC+ environment variable or defaults to +$HOME/.fog+
    # @return [String] The path for configuration_file
    #
    # source://fog-core//lib/fog/core/credentials.rb#50
    def credentials_path; end

    # @return [String] The new path for credentials file
    #
    # source://fog-core//lib/fog/core/credentials.rb#60
    def credentials_path=(new_credentials_path); end

    # Returns the value of attribute interval.
    #
    # source://fog-core//lib/fog/core/wait_for_defaults.rb#5
    def interval; end

    # source://fog-core//lib/fog/core/wait_for_defaults.rb#8
    def interval=(interval); end

    # Returns the value of attribute max_interval.
    #
    # source://fog-core//lib/fog/core/wait_for_defaults.rb#32
    def max_interval; end

    # @raise [ArgumentError]
    #
    # source://fog-core//lib/fog/core/wait_for_defaults.rb#35
    def max_interval=(interval); end

    # source://fog-core//lib/fog/core/mock.rb#4
    def mock!; end

    # Returns the value of attribute mocking.
    #
    # source://fog-core//lib/fog/core/mock.rb#15
    def mock?; end

    # Returns the value of attribute mocking.
    #
    # source://fog-core//lib/fog/core/mock.rb#13
    def mocking; end

    # Returns the value of attribute mocking.
    #
    # source://fog-core//lib/fog/core/mock.rb#16
    def mocking?; end

    # source://fog-core//lib/fog/core/provider.rb#6
    def providers; end

    # Sets the attribute providers
    #
    # @param value the value to set the attribute providers to.
    #
    # source://fog-core//lib/fog/core/provider.rb#3
    def providers=(_arg0); end

    # source://fog-core//lib/fog/core/service.rb#4
    def services; end

    # @deprecated Don't use!
    # @param key [Object]
    # @return [true] if key == :headers
    #
    # source://fog-core//lib/fog/core/credentials.rb#81
    def symbolize_credential?(key); end

    # @deprecated Use {Fog::Core::Utils.prepare_service_settings} instead
    #
    # source://fog-core//lib/fog/core/credentials.rb#86
    def symbolize_credentials(hash); end

    # Returns the value of attribute timeout.
    #
    # source://fog-core//lib/fog/core/wait_for_defaults.rb#20
    def timeout; end

    # @raise [ArgumentError]
    #
    # source://fog-core//lib/fog/core/wait_for_defaults.rb#23
    def timeout=(timeout); end

    # source://fog-core//lib/fog/core/mock.rb#8
    def unmock!; end

    # source://fog-core//lib/fog/core/wait_for.rb#2
    def wait_for(timeout = T.unsafe(nil), interval = T.unsafe(nil), &_block); end
  end
end

class Fog::AWS::CDN < ::Fog::Service; end
module Fog::AWS::CDN::Collections; end
class Fog::AWS::Compute < ::Fog::Service; end
module Fog::AWS::Compute::Collections; end
class Fog::AWS::DNS < ::Fog::Service; end
module Fog::AWS::DNS::Collections; end
class Fog::AWS::Storage < ::Fog::Service; end
module Fog::AWS::Storage::Collections; end

# source://fog-core//lib/fog/account.rb#2
module Fog::Account
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/core/association.rb#2
class Fog::Association < ::Fog::Collection
  # @return [Association] a new instance of Association
  #
  # source://fog-core//lib/fog/core/association.rb#3
  def initialize(associations = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/association.rb#8
  def load(associations); end
end

# source://fog-core//lib/fog/core/associations/default.rb#2
module Fog::Associations; end

# = Fog Default Association
#
# This class has the shared behavior between all association models.
#
# source://fog-core//lib/fog/core/associations/default.rb#6
class Fog::Associations::Default
  # @return [Default] a new instance of Default
  #
  # source://fog-core//lib/fog/core/associations/default.rb#9
  def initialize(model, name, collection_name, options); end

  # Returns the value of attribute aliases.
  #
  # source://fog-core//lib/fog/core/associations/default.rb#7
  def aliases; end

  # Returns the value of attribute as.
  #
  # source://fog-core//lib/fog/core/associations/default.rb#7
  def as; end

  # Returns the value of attribute association_class.
  #
  # source://fog-core//lib/fog/core/associations/default.rb#7
  def association_class; end

  # source://fog-core//lib/fog/core/associations/default.rb#22
  def create_aliases; end

  # source://fog-core//lib/fog/core/associations/default.rb#28
  def create_mask; end

  # Returns the value of attribute model.
  #
  # source://fog-core//lib/fog/core/associations/default.rb#7
  def model; end

  # Returns the value of attribute name.
  #
  # source://fog-core//lib/fog/core/associations/default.rb#7
  def name; end
end

# = Fog Multiple Association
#
# This class handles multiple association between the models.
# It expects the provider to return a collection of ids.
# The association models will be loaded based on the collection of ids.
#
# source://fog-core//lib/fog/core/associations/many_identities.rb#8
class Fog::Associations::ManyIdentities < ::Fog::Associations::Default
  # source://fog-core//lib/fog/core/associations/many_identities.rb#19
  def create_getter; end

  # source://fog-core//lib/fog/core/associations/many_identities.rb#9
  def create_setter; end
end

# = Fog Multiple Association
#
# This class handles multiple association between the models.
# It expects the provider to map the attribute with a collection of objects.
#
# source://fog-core//lib/fog/core/associations/many_models.rb#7
class Fog::Associations::ManyModels < ::Fog::Associations::Default
  # source://fog-core//lib/fog/core/associations/many_models.rb#16
  def create_getter; end

  # source://fog-core//lib/fog/core/associations/many_models.rb#8
  def create_setter; end
end

# = Fog Single Association
#
# This class handles single association between the models.
# It expects the provider to return only the id of the association.
# The association model will be loaded based on the id initialized.
#
# source://fog-core//lib/fog/core/associations/one_identity.rb#8
class Fog::Associations::OneIdentity < ::Fog::Associations::Default
  # source://fog-core//lib/fog/core/associations/one_identity.rb#17
  def create_getter; end

  # source://fog-core//lib/fog/core/associations/one_identity.rb#9
  def create_setter; end
end

# = Fog Single Association
#
# This class handles single association between the models.
# It expects the provider to map the attribute with an initialized object.
#
# source://fog-core//lib/fog/core/associations/one_model.rb#7
class Fog::Associations::OneModel < ::Fog::Associations::Default
  # source://fog-core//lib/fog/core/associations/one_model.rb#16
  def create_getter; end

  # source://fog-core//lib/fog/core/associations/one_model.rb#8
  def create_setter; end
end

# source://fog-core//lib/fog/core/attributes.rb#2
module Fog::Attributes; end

# = Fog Array Attribute
#
# This class handles Array attributes from the providers,
# converting values to Array objects
#
# source://fog-core//lib/fog/core/attributes/array.rb#7
class Fog::Attributes::Array < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/array.rb#16
  def create_getter; end

  # source://fog-core//lib/fog/core/attributes/array.rb#8
  def create_setter; end
end

# = Fog Boolean Attribute
#
# This class handles Boolean attributes from the providers,
# converting values to Boolean objects
#
# source://fog-core//lib/fog/core/attributes/boolean.rb#7
class Fog::Attributes::Boolean < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/boolean.rb#8
  def create_setter; end
end

# source://fog-core//lib/fog/core/attributes.rb#3
module Fog::Attributes::ClassMethods
  # source://fog-core//lib/fog/core/attributes.rb#4
  def _load(marshalled); end

  # source://fog-core//lib/fog/core/attributes.rb#8
  def aliases; end

  # source://fog-core//lib/fog/core/attributes.rb#12
  def associations; end

  # Defines a new attribute
  #
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @param name [Symbol] attribute name
  # @param options [Hash] (see {Default#initialize})
  #
  # source://fog-core//lib/fog/core/attributes.rb#36
  def attribute(name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#16
  def attributes; end

  # source://fog-core//lib/fog/core/attributes.rb#20
  def default_values; end

  # source://fog-core//lib/fog/core/attributes.rb#45
  def has_many(name, collection_name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#53
  def has_many_identities(name, collection_name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#41
  def has_one(name, collection_name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#49
  def has_one_identity(name, collection_name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#57
  def identity(name, options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/attributes.rb#62
  def ignore_attributes(*args); end

  # source://fog-core//lib/fog/core/attributes.rb#66
  def ignored_attributes; end

  # source://fog-core//lib/fog/core/attributes.rb#24
  def masks; end
end

# = Fog Default Attribute
#
# This class handles the attributes without a type force.
# The attributes returned from the provider will keep its original values.
#
# source://fog-core//lib/fog/core/attributes/default.rb#7
class Fog::Attributes::Default
  # @option options
  # @option options
  # @option options
  # @option options
  # @param model [Klass] model class
  # @param name [Symbol] name of the attribute
  # @param options [Hash] attribute options
  # @return [Default] a new instance of Default
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#17
  def initialize(model, name, options); end

  # Returns the value of attribute aliases.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def aliases; end

  # Returns the value of attribute as.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def as; end

  # source://fog-core//lib/fog/core/attributes/default.rb#70
  def create_aliases; end

  # source://fog-core//lib/fog/core/attributes/default.rb#58
  def create_getter; end

  # source://fog-core//lib/fog/core/attributes/default.rb#80
  def create_mask; end

  # source://fog-core//lib/fog/core/attributes/default.rb#32
  def create_setter; end

  # Returns the value of attribute default.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def default; end

  # Returns the value of attribute model.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def model; end

  # Returns the value of attribute name.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def name; end

  # source://fog-core//lib/fog/core/attributes/default.rb#76
  def set_defaults; end

  # Returns the value of attribute squash.
  #
  # source://fog-core//lib/fog/core/attributes/default.rb#8
  def squash; end
end

# = Fog Float Attribute
#
# This class handles Float attributes from the providers,
# converting values to Float objects
#
# source://fog-core//lib/fog/core/attributes/float.rb#7
class Fog::Attributes::Float < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/float.rb#8
  def create_setter; end
end

# source://fog-core//lib/fog/core/attributes.rb#71
module Fog::Attributes::InstanceMethods
  # source://fog-core//lib/fog/core/attributes.rb#72
  def _dump(_level); end

  # source://fog-core//lib/fog/core/attributes.rb#101
  def all_associations; end

  # source://fog-core//lib/fog/core/attributes.rb#114
  def all_associations_and_attributes; end

  # source://fog-core//lib/fog/core/attributes.rb#88
  def all_attributes; end

  # source://fog-core//lib/fog/core/attributes.rb#80
  def associations; end

  # source://fog-core//lib/fog/core/attributes.rb#76
  def attributes; end

  # source://fog-core//lib/fog/core/attributes.rb#118
  def dup; end

  # Filters attributes by selected attribute names
  #
  # @note In some cases we want to easily get subset of model attributes
  # @note Hash#slice requires Ruby >= 2.5.0
  # @param selected [Symbol] attribute names
  # @return [Hash] new hash with selected attributes
  #
  # source://fog-core//lib/fog/core/attributes.rb#159
  def filter_attributes(*selected); end

  # source://fog-core//lib/fog/core/attributes.rb#128
  def identity; end

  # source://fog-core//lib/fog/core/attributes.rb#132
  def identity=(new_identity); end

  # source://fog-core//lib/fog/core/attributes.rb#124
  def identity_name; end

  # source://fog-core//lib/fog/core/attributes.rb#84
  def masks; end

  # Merges attributes into self
  #
  # @note Ignored attributes are not merged (see {ClassMethods.ignored_attributes})
  # @return [self]
  #
  # source://fog-core//lib/fog/core/attributes.rb#139
  def merge_attributes(new_attributes = T.unsafe(nil)); end

  # Returns true if a remote resource has not been assigned an
  # identity.
  #
  # This was added for a ActiveRecord like feel but has been
  # outdated by ActiveModel API using {#persisted?}
  #
  # @deprecated Use inverted form of {#persisted?}
  # @return [Boolean]
  #
  # source://fog-core//lib/fog/core/attributes.rb#182
  def new_record?; end

  # Returns true if a remote resource has been assigned an
  # identity and we can assume it has been persisted.
  #
  # @return [Boolean]
  #
  # source://fog-core//lib/fog/core/attributes.rb#170
  def persisted?; end

  # check that the attributes specified in args exist and is not nil
  #
  # source://fog-core//lib/fog/core/attributes.rb#188
  def requires(*args); end

  # @raise [ArgumentError]
  #
  # source://fog-core//lib/fog/core/attributes.rb#197
  def requires_one(*args); end

  protected

  # source://fog-core//lib/fog/core/attributes.rb#214
  def dup_attributes!; end

  # source://fog-core//lib/fog/core/attributes.rb#206
  def missing_attributes(args); end

  private

  # source://fog-core//lib/fog/core/attributes.rb#220
  def remap_attributes(attributes, mapping); end
end

# = Fog Integer Attribute
#
# This class handles Integer attributes from the providers,
# converting values to Integer objects
#
# source://fog-core//lib/fog/core/attributes/integer.rb#7
class Fog::Attributes::Integer < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/integer.rb#8
  def create_setter; end
end

# = Fog String Attribute
#
# This class handles String attributes from the providers,
# converting values to String objects
#
# source://fog-core//lib/fog/core/attributes/string.rb#7
class Fog::Attributes::String < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/string.rb#8
  def create_setter; end
end

# = Fog Time Attribute
#
# This class handles Time attributes from the providers,
# converting values to Time objects
#
# source://fog-core//lib/fog/core/attributes/time.rb#7
class Fog::Attributes::Time < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/time.rb#8
  def create_setter; end
end

# = Fog Timestamp Attribute
#
# This class handles Timestamp attributes from the providers,
# converting Integer and String values as a real Timestamp objects
#
# source://fog-core//lib/fog/core/attributes/timestamp.rb#7
class Fog::Attributes::Timestamp < ::Fog::Attributes::Default
  # source://fog-core//lib/fog/core/attributes/timestamp.rb#8
  def create_setter; end
end

# source://fog-core//lib/fog/baremetal.rb#2
module Fog::Baremetal
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/billing.rb#2
module Fog::Billing
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/cdn.rb#2
module Fog::CDN
  extend ::Fog::ServicesMixin
end

class Fog::CDN::AWS < ::Fog::AWS::CDN; end
module Fog::CDN::AWS::Collections; end

# A generic cache mechanism for fog resources. This can be for a server, security group, etc.
#
# Currently this is a on-disk cache using yml files per-model instance, however
# there is nothing in the way of extending this to use various other cache
# backends.
#
# == Basic functionality
#
# set the namespace where this cache will be stored:
#
# Fog::Cache.namespace_prefix = "service-account-foo-region-bar"
#
# cache to disk:
#
#   # after dumping, there will be a yml file on disk:
#   resouce.cache.dump
#
#   # you can load cached data in from a different session
#   Fog::Cache.load(Fog::Compute::AWS::Server, compute)
#
#   # you can also expire cache (removes cached data assocaited with the resources of this model associated to the service passed in).
#   Fog::Cache.expire_cache!(Fog::Compute::AWS::Server, compute)
#
# == More detailed flow/usage
#
# Normally, you would have a bunch of resources you want to cache/reload from disk.
# Every fog model has a +cache+ object injected to accomplish this. So in order to cache a server for exmaple
# you would do something like this:
#
#   # note this is necessary in order to segregate usage of cache between various providers regions and accounts.
#   # if you are using one account/region/etc only, you still must set it. 'default' will do.
#   Fog::Cache.namespace_prefix = "prod-emea-eu-west-1"
#
#   s = security_groups.sample; s.name # => "default"
#   s.cache.dump # => 2371
#
# Now it is on disk:
#
# shai@adsk-lappy ~   % tree ~/.fog-cache/prod-emea-eu-west-1/
#
#   /Users/shai/.fog-cache/prod-emea-eu-west-1/
#     └── fog_compute_aws_real
#       └── fog_compute_aws_securitygroup
#        ├── default-90928073d9d5d9b4e7545e88aee7ec4f.yml
#
# You can do the same with a SecurityGroup, Instances, Elbs, etc.
#
# Note that when loading cache from disk, you need to pass the appropriate model class, and service associated with it.
# +Service+ is passed in is so that the service/connection details can be loaded into the loaded instances so they can be re-queried, etc.
# +Model+ is passed in so we can find the cache data associated to that model in the namespace of cache this session is using:
# Will try to load all resources associated to those. If you had 1 yml file, or 100, it would load whatever it could find.
# As such, the normal usage of dumping would be do it on a collection:
#
#   load_balancers.each {|elb| elb.cache.dump }
#
# In order to load the cache into a different session with nothing but the service set up, use like so:
# As mentioned, will load all resources associated to the +model_klass+ and +service+ passed in.
#
#   instances = Fog::Cache.load(Fog::Compute::AWS::Server, compute)
#   instances.first.id # => "i-0569a70ae6f47d229"
#
# Note that if there is no cache located for the +model+ class and +service+ passed to `Fog::Cache.load`
# you will get an exception you can handle (for example, to load the resources for the fisrt time):
#
#   Fog::Cache.expire_cache!(Fog::Compute::AWS::SecurityGroup, compute)
#   # ... now there is no SecurityGroup cache data. So, if you tried to load it, you would get an exception:
#
#   Fog::Cache.load(Fog::Compute::AWS::SecurityGroup, compute)
#     rescue Fog::Cache::CacheNotFound => e
#       puts "could not find any cache data for security groups on #{compute}"
#       get_resources_and_dump
#
# == Extending cache backends
#
# Currently this is on-disk using yml. If need be, this could be extended to other cache backends:
#
# Find references of yaml in this file, split out to strategy objects/diff backends etc.
#
# source://fog-core//lib/fog/core/cache.rb#84
class Fog::Cache
  # @return [Cache] a new instance of Cache
  #
  # source://fog-core//lib/fog/core/cache.rb#260
  def initialize(model); end

  # Dump a Fog::Model resource. Every fog model/instance now has a +cache+ method/object injected in.
  # as such you can use the #dump method to save the attributes and metadata of that instance as cache
  # which can be re-used in some other session.
  #
  # source://fog-core//lib/fog/core/cache.rb#267
  def dump; end

  # the location of where to save this fog model/instance to.
  #
  # source://fog-core//lib/fog/core/cache.rb#284
  def dump_to; end

  # when a resource is used such as `server.cache.dump` the model klass is passed in
  # so that it can be identified from a different session.
  #
  # source://fog-core//lib/fog/core/cache.rb#101
  def model; end

  class << self
    # cleans the `SANDBOX` - specific any resource cache of any namespace,
    # and any metadata associated to any.
    #
    # source://fog-core//lib/fog/core/cache.rb#183
    def clean!; end

    # creates on-disk cache of this specific +model_klass+ and +@service+
    #
    # source://fog-core//lib/fog/core/cache.rb#171
    def create_namespace(model_klass, service); end

    # Expires cache - this does not expire all cache associated.
    # Instead, this will remove all on-disk cache of this specific +model_klass+ and and +@service+
    #
    # source://fog-core//lib/fog/core/cache.rb#177
    def expire_cache!(model_klass, service); end

    # Loads cache associated to the +model_klass+ and +service+ into memory.
    #
    # If no cache is found, it will raise an error for handling:
    #
    #   rescue Fog::Cache::CacheNotFound
    #     set_initial_cache
    #
    # @raise [CacheNotFound]
    #
    # source://fog-core//lib/fog/core/cache.rb#110
    def load(model_klass, service); end

    # loads yml cache from path on disk, used
    # to initialize Fog models.
    #
    # source://fog-core//lib/fog/core/cache.rb#199
    def load_cache(path); end

    # retrive metadata for this +namespace+ of cache. returns empty {} if none found.
    #
    # source://fog-core//lib/fog/core/cache.rb#239
    def metadata; end

    # The path/namespace where the cache is stored for a specific +model_klass+ and +@service+.
    #
    # @raise [CacheDir]
    #
    # source://fog-core//lib/fog/core/cache.rb#249
    def namespace(model_klass, service); end

    # source://fog-core//lib/fog/core/cache.rb#210
    def namespace_prefix; end

    # source://fog-core//lib/fog/core/cache.rb#206
    def namespace_prefix=(name); end

    # source://fog-core//lib/fog/core/cache.rb#256
    def safe_class_path(klass); end

    # method to determine if a path can be loaded and is valid fog cache format.
    #
    # @return [Boolean]
    #
    # source://fog-core//lib/fog/core/cache.rb#157
    def valid_for_load?(path); end

    # write any metadata - +hash+ information - specific to the namespaced cache in the session.
    #
    # you can retrieve this in other sessions, as long as +namespace_prefix+ is set
    # you can overwrite metadata over time. see test cases as examples.
    #
    # source://fog-core//lib/fog/core/cache.rb#218
    def write_metadata(h); end

    # Load YAML file with aliases
    #
    # @note Starting from Ruby 3.1 we must explicitly tell Psych to allow aliases
    #
    # source://fog-core//lib/fog/core/cache.rb#189
    def yaml_load(path); end
  end
end

# cache directory problem
#
# source://fog-core//lib/fog/core/cache.rb#90
class Fog::Cache::CacheDir < ::StandardError; end

# cache associated not found
#
# source://fog-core//lib/fog/core/cache.rb#87
class Fog::Cache::CacheNotFound < ::StandardError; end

# required attributes to load model from cache
#
# source://fog-core//lib/fog/core/cache.rb#97
Fog::Cache::REQUIRED_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# where different caches per +service+ api keys, regions etc, are stored
# see the +namespace_prefix=+ method.
#
# source://fog-core//lib/fog/core/cache.rb#94
Fog::Cache::SANDBOX = T.let(T.unsafe(nil), String)

# Fog::Collection
#
# source://fog-core//lib/fog/core/collection.rb#5
class Fog::Collection < ::Array
  include ::Fog::Attributes::InstanceMethods
  include ::Fog::Core::DeprecatedConnectionAccessors
  extend ::Fog::Attributes::ClassMethods

  # Creates a new Fog::Collection based around the passed service
  #
  # @option attributes
  # @param attributes [Hash]
  # @return [Fog::Collection]
  #
  # source://fog-core//lib/fog/core/collection.rb#68
  def initialize(attributes = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def &(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def *(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def +(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def -(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def <<(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def <=>(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def ==(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def [](*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def []=(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def all?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def any?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def append(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def as_json(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def assoc(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def at(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def blank?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def bsearch(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def bsearch_index(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#47
  def clear; end

  # source://fog-core//lib/fog/core/collection.rb#15
  def collect(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def collect!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def combination(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def compact(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def compact!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def compact_blank!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def concat(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def count(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#51
  def create(attributes = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def cycle(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def deconstruct(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def deep_dup(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def delete(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def delete_at(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def delete_if(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#57
  def destroy(identity); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def difference(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def dig(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def drop(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def drop_while(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def each(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def each_index(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def empty?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def eql?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def excluding(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def extract_options!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def fetch(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def fifth(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def fill(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def filter(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def filter!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def find_index(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def first(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def flatten(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def flatten!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def forty_two(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def fourth(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def from(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def hash(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def include?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def including(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def index(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def insert(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#74
  def inspect; end

  # source://fog-core//lib/fog/core/collection.rb#15
  def intersect?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def intersection(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def join(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def keep_if(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def last(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def length(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#78
  def load(objects); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def map(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def map!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def max(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def min(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def minmax(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#83
  def model; end

  # source://fog-core//lib/fog/core/collection.rb#87
  def new(attributes = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def none?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def one?(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def pack(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def permutation(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def place(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def pop(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def prepend(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def pretty_print(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def pretty_print_cycle(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def product(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def push(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def rassoc(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#27
  def reject(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def reject!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#100
  def reload; end

  # source://fog-core//lib/fog/core/collection.rb#15
  def repeated_combination(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def repeated_permutation(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def replace(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def reverse(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def reverse!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def reverse_each(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def rindex(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def rotate(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def rotate!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def sample(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def second(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def second_to_last(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#27
  def select(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def select!(*args, **_arg1); end

  # Returns the value of attribute service.
  #
  # source://fog-core//lib/fog/core/collection.rb#10
  def service; end

  # source://fog-core//lib/fog/core/collection.rb#15
  def shelljoin(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def shift(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def shuffle(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def shuffle!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def size(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#27
  def slice(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def slice!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def sort(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def sort!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def sort_by!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def sum(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#105
  def table(attributes = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def take(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def take_while(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def third(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def third_to_last(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_a(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_ary(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_default_s(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_formatted_s(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_fs(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_h(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#109
  def to_json(_options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_param(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_query(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_s(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_sentence(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def to_xml(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def transpose(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def union(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def uniq(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def uniq!(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def unshift(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def values_at(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def without(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def zip(*args, **_arg1); end

  # source://fog-core//lib/fog/core/collection.rb#15
  def |(*args, **_arg1); end

  private

  # source://fog-core//lib/fog/core/collection.rb#115
  def lazy_load; end

  class << self
    # source://fog-core//lib/fog/core/collection.rb#39
    def model(new_model = T.unsafe(nil)); end
  end
end

# source://fog-core//lib/fog/compute.rb#2
module Fog::Compute
  extend ::Fog::ServicesMixin

  class << self
    # source://fog-core//lib/fog/compute.rb#5
    def new(orig_attributes); end

    # source://fog-core//lib/fog/compute.rb#36
    def servers; end
  end
end

class Fog::Compute::AWS < ::Fog::AWS::Compute; end
module Fog::Compute::AWS::Collections; end

# source://fog-core//lib/fog/core/version.rb#4
module Fog::Core; end

# Fog::Core::Connection is a generic class to contain a HTTP link to an API.
#
# It is intended to be subclassed by providers who can then add their own
# modifications such as authentication or response object.
#
# source://fog-core//lib/fog/core/connection.rb#8
class Fog::Core::Connection
  # Prepares the connection and sets defaults for any future requests.
  #
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash]
  # @param persistent [Boolean]
  # @param url [String] The destination URL
  # @return [Connection] a new instance of Connection
  #
  # source://fog-core//lib/fog/core/connection.rb#46
  def initialize(url, persistent = T.unsafe(nil), params = T.unsafe(nil)); end

  # Makes a request using the connection using Excon
  #
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash]
  # @raise [Excon::Errors::StubNotFound]
  # @raise [Excon::Errors::Timeout]
  # @raise [Excon::Errors::SocketError]
  # @return [Excon::Response]
  #
  # source://fog-core//lib/fog/core/connection.rb#78
  def request(params, &block); end

  # Closes the connection
  #
  # source://fog-core//lib/fog/core/connection.rb#90
  def reset; end

  protected

  # Makes a request using the connection using Excon
  # Make {#request} available even when it has been overidden by a subclass
  # to allow backwards compatibility.
  #
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @option params
  # @param params [Hash]
  # @raise [Excon::Errors::StubNotFound]
  # @raise [Excon::Errors::Timeout]
  # @raise [Excon::Errors::SocketError]
  # @return [Excon::Response]
  #
  # source://fog-core//lib/fog/core/connection.rb#85
  def original_request(params, &block); end

  private

  # source://fog-core//lib/fog/core/connection.rb#100
  def handle_path_prefix_for(params); end

  # source://fog-core//lib/fog/core/connection.rb#96
  def user_agent; end

  class << self
    # source://fog-core//lib/fog/core/connection.rb#13
    def add_user_agent(str); end

    # source://fog-core//lib/fog/core/connection.rb#21
    def user_agents; end
  end
end

# This module covers the shared code used by models and collections
# that deprecates the confusing usage of 'connection' which was
# actually intended to be an instance of Fog::Service
#
# source://fog-core//lib/fog/core/deprecated_connection_accessors.rb#6
module Fog::Core::DeprecatedConnectionAccessors
  # Returns the Service the collection is part of
  #
  # @deprecated #connection is deprecated due to confusing name, use #service instead
  # @return [Fog::Service]
  #
  # source://fog-core//lib/fog/core/deprecated_connection_accessors.rb#22
  def connection; end

  # Sets the Service but using the wrong name!
  #
  # @deprecated The connection name was wrong and confusing since it refered to the service
  # @param service [Fog::Service] An instance of a Fog service this collection is for
  #
  # source://fog-core//lib/fog/core/deprecated_connection_accessors.rb#12
  def connection=(service); end

  # Prepares the value of the service based on the passed attributes
  #
  # @note Intended for use where the service is required before the normal
  #   initializer runs. The logic is run there with deprecation warnings.
  # @param attributes [Hash]
  # @return [Fog::Service]
  #
  # source://fog-core//lib/fog/core/deprecated_connection_accessors.rb#35
  def prepare_service_value(attributes); end
end

# source://fog-core//lib/fog/core/utils.rb#3
module Fog::Core::Utils
  class << self
    # This helper prepares a Hash of settings for passing into {Fog::Service.new}.
    #
    # The only special consideration is if +:header+ key is passed in the contents are unchanged. This
    # allows the headers to be passed through to requests to customise HTTP headers without them being
    # broken by the +#to_sym+ calls.
    #
    # @option settings
    # @param settings [Hash] The String based Hash to prepare
    # @return [Hash]
    #
    # source://fog-core//lib/fog/core/utils.rb#14
    def prepare_service_settings(settings); end
  end
end

# source://fog-core//lib/fog/core/version.rb#5
Fog::Core::VERSION = T.let(T.unsafe(nil), String)

# source://fog-core//lib/fog/core/current_machine.rb#4
class Fog::CurrentMachine
  class << self
    # Get the ip address of the machine from which this command is run. It is
    # recommended that you surround calls to this function with a timeout block
    # to ensure optimum performance in the case where the amazonaws checkip
    # service is unavailable.
    #
    # @example Get the current ip address
    #   begin
    #   Timeout::timeout(5) do
    #   puts "Your ip address is #{Fog::CurrentMachine.ip_address}"
    #   end
    #   rescue Timeout::Error
    #   puts "Service timeout"
    #   end
    # @raise [Excon::Errors::Error] if the net/http request fails.
    #
    # source://fog-core//lib/fog/core/current_machine.rb#30
    def ip_address; end

    # source://fog-core//lib/fog/core/current_machine.rb#9
    def ip_address=(ip_address); end
  end
end

# source://fog-core//lib/fog/core/current_machine.rb#7
Fog::CurrentMachine::AMAZON_AWS_CHECK_IP = T.let(T.unsafe(nil), String)

# source://fog-core//lib/fog/dns.rb#2
module Fog::DNS
  extend ::Fog::ServicesMixin

  class << self
    # source://fog-core//lib/fog/dns.rb#5
    def zones; end
  end
end

class Fog::DNS::AWS < ::Fog::AWS::DNS; end
module Fog::DNS::AWS::Collections; end

# source://fog-core//lib/fog/core/deprecation.rb#2
module Fog::Deprecation
  # source://fog-core//lib/fog/core/deprecation.rb#3
  def deprecate(older, newer); end

  # source://fog-core//lib/fog/core/deprecation.rb#12
  def self_deprecate(older, newer); end
end

# source://fog-core//lib/fog/core/errors.rb#2
module Fog::Errors
  class << self
    # @raise [Fog::Errors::LoadError]
    # @return [String] The error message that will be raised, if credentials cannot be found
    #
    # source://fog-core//lib/fog/core/errors.rb#25
    def missing_credentials; end
  end
end

# source://fog-core//lib/fog/core/errors.rb#3
class Fog::Errors::Error < ::StandardError
  # Returns the value of attribute verbose.
  #
  # source://fog-core//lib/fog/core/errors.rb#4
  def verbose; end

  # Sets the attribute verbose
  #
  # @param value the value to set the attribute verbose to.
  #
  # source://fog-core//lib/fog/core/errors.rb#4
  def verbose=(_arg0); end

  class << self
    # source://fog-core//lib/fog/core/errors.rb#6
    def slurp(error, message = T.unsafe(nil)); end
  end
end

# source://fog-core//lib/fog/core/errors.rb#18
class Fog::Errors::LoadError < ::Fog::Errors::Error; end

# source://fog-core//lib/fog/core/errors.rb#14
class Fog::Errors::MockNotImplemented < ::Fog::Errors::Error; end

# source://fog-core//lib/fog/core/errors.rb#16
class Fog::Errors::NotFound < ::Fog::Errors::Error; end

# source://fog-core//lib/fog/core/errors.rb#22
class Fog::Errors::NotImplemented < ::Fog::Errors::Error; end

# source://fog-core//lib/fog/core/errors.rb#20
class Fog::Errors::TimeoutError < ::Fog::Errors::Error; end

# Fog::Formatador
#
# source://fog-core//lib/fog/formatador.rb#3
module Fog::Formatador
  class << self
    # source://fog-core//lib/fog/formatador.rb#56
    def attribute_string(object); end

    # source://fog-core//lib/fog/formatador.rb#26
    def display_compact_table(hashes, keys = T.unsafe(nil), &block); end

    # source://fog-core//lib/fog/formatador.rb#18
    def display_line(data); end

    # source://fog-core//lib/fog/formatador.rb#22
    def display_lines(data); end

    # source://fog-core//lib/fog/formatador.rb#30
    def display_table(hashes, keys = T.unsafe(nil), &block); end

    # source://fog-core//lib/fog/formatador.rb#12
    def format(object, opts = T.unsafe(nil)); end

    # source://fog-core//lib/fog/formatador.rb#8
    def formatador; end

    # source://fog-core//lib/fog/formatador.rb#38
    def indent(&block); end

    # source://fog-core//lib/fog/formatador.rb#42
    def indentation; end

    # source://fog-core//lib/fog/formatador.rb#46
    def init_string(object); end

    # source://fog-core//lib/fog/formatador.rb#83
    def inspect_object(object); end

    # source://fog-core//lib/fog/formatador.rb#66
    def nested_objects_string(object); end

    # source://fog-core//lib/fog/formatador.rb#76
    def object_attributes(object); end

    # source://fog-core//lib/fog/formatador.rb#50
    def object_string(object, opts); end

    # source://fog-core//lib/fog/formatador.rb#34
    def redisplay_progressbar(current, total, options = T.unsafe(nil)); end
  end
end

# source://fog-core//lib/fog/formatador.rb#6
Fog::Formatador::INDENT_REGEX = T.let(T.unsafe(nil), Regexp)

# source://fog-core//lib/fog/formatador.rb#4
Fog::Formatador::PARSE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://fog-core//lib/fog/formatador.rb#5
Fog::Formatador::STYLES = T.let(T.unsafe(nil), Hash)

# source://fog-core//lib/fog/core/hmac.rb#2
class Fog::HMAC
  # @return [HMAC] a new instance of HMAC
  #
  # source://fog-core//lib/fog/core/hmac.rb#3
  def initialize(type, key); end

  # source://fog-core//lib/fog/core/hmac.rb#13
  def sign(data); end

  private

  # source://fog-core//lib/fog/core/hmac.rb#19
  def setup_sha1; end

  # source://fog-core//lib/fog/core/hmac.rb#26
  def setup_sha256; end
end

# source://fog-core//lib/fog/identity.rb#2
module Fog::Identity
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/image.rb#2
module Fog::Image
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/introspection.rb#2
module Fog::Introspection
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/core/logger.rb#2
class Fog::Logger
  class << self
    # source://fog-core//lib/fog/core/logger.rb#13
    def [](channel); end

    # source://fog-core//lib/fog/core/logger.rb#17
    def []=(channel, value); end

    # source://fog-core//lib/fog/core/logger.rb#21
    def debug(message); end

    # source://fog-core//lib/fog/core/logger.rb#25
    def deprecation(message); end

    # source://fog-core//lib/fog/core/logger.rb#29
    def warning(message); end

    # source://fog-core//lib/fog/core/logger.rb#33
    def write(key, value); end
  end
end

# source://fog-core//lib/fog/metering.rb#2
module Fog::Metering
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/core/mock.rb#19
module Fog::Mock
  class << self
    # Returns the value of attribute delay.
    #
    # source://fog-core//lib/fog/core/mock.rb#23
    def delay; end

    # @raise [ArgumentError]
    #
    # source://fog-core//lib/fog/core/mock.rb#26
    def delay=(new_delay); end

    # @raise [Fog::Errors::MockNotImplemented]
    #
    # source://fog-core//lib/fog/core/mock.rb#32
    def not_implemented(message = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/mock.rb#52
    def random_base64(length); end

    # source://fog-core//lib/fog/core/mock.rb#59
    def random_hex(length); end

    # source://fog-core//lib/fog/core/mock.rb#36
    def random_ip(opts = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/mock.rb#64
    def random_letters(length); end

    # source://fog-core//lib/fog/core/mock.rb#76
    def random_letters_and_numbers(length); end

    # source://fog-core//lib/fog/core/mock.rb#71
    def random_numbers(length); end

    # source://fog-core//lib/fog/core/mock.rb#83
    def random_selection(characters, length); end

    # source://fog-core//lib/fog/core/mock.rb#92
    def reset; end
  end
end

# source://fog-core//lib/fog/core/model.rb#5
class Fog::Model
  include ::Fog::Attributes::InstanceMethods
  include ::Fog::Core::DeprecatedConnectionAccessors
  extend ::Fog::Attributes::ClassMethods

  # @return [Model] a new instance of Model
  #
  # source://fog-core//lib/fog/core/model.rb#13
  def initialize(new_attributes = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/model.rb#59
  def ==(o); end

  # source://fog-core//lib/fog/core/model.rb#51
  def cache; end

  # Returns the value of attribute collection.
  #
  # source://fog-core//lib/fog/core/model.rb#10
  def collection; end

  # Sets the attribute collection
  #
  # @param value the value to set the attribute collection to.
  #
  # source://fog-core//lib/fog/core/model.rb#10
  def collection=(_arg0); end

  # Creates new entity from model
  #
  # @raise [Fog::Errors::NotImplemented] you must implement #create method in child class and return self
  # @return [self]
  #
  # source://fog-core//lib/fog/core/model.rb#33
  def create; end

  # Destroys entity by model identity
  #
  # @raise [Fog::Errors::NotImplemented] you must implement #destroy method in child class and return self
  # @return [self]
  #
  # source://fog-core//lib/fog/core/model.rb#47
  def destroy; end

  # source://fog-core//lib/fog/core/model.rb#55
  def inspect; end

  # @return [self] if model successfully reloaded
  # @return [nil] if something went wrong or model was not found
  #
  # source://fog-core//lib/fog/core/model.rb#73
  def reload; end

  # Creates new or updates existing model
  #
  # @return [self]
  #
  # source://fog-core//lib/fog/core/model.rb#26
  def save; end

  # Returns the value of attribute service.
  #
  # source://fog-core//lib/fog/core/model.rb#11
  def service; end

  # source://fog-core//lib/fog/core/model.rb#91
  def symbolize_keys(hash); end

  # source://fog-core//lib/fog/core/model.rb#87
  def to_json(_options = T.unsafe(nil)); end

  # Updates new entity with model
  #
  # @raise [Fog::Errors::NotImplemented] you must implement #update method in child class and return self
  # @return [self]
  #
  # source://fog-core//lib/fog/core/model.rb#40
  def update; end

  # @raise [Fog::Errors::Error]
  #
  # source://fog-core//lib/fog/core/model.rb#100
  def wait_for(timeout = T.unsafe(nil), interval = T.unsafe(nil), &block); end
end

# source://fog-core//lib/fog/monitoring.rb#2
module Fog::Monitoring
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/nfv.rb#2
module Fog::NFV
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/network.rb#2
module Fog::Network
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/orchestration.rb#2
module Fog::Orchestration
  extend ::Fog::ServicesMixin
end

# Base class for collection classes whose 'all' method returns only a single
# page of results and passes the 'Marker' option along as
# self.filters[:marker]
#
# source://fog-core//lib/fog/core/collection.rb#123
class Fog::PagedCollection < ::Fog::Collection
  # source://fog-core//lib/fog/core/collection.rb#124
  def each(collection_filters = T.unsafe(nil)); end
end

# source://fog-core//lib/fog/core/provider.rb#10
module Fog::Provider
  # source://fog-core//lib/fog/core/provider.rb#29
  def [](service_key); end

  # source://fog-core//lib/fog/core/provider.rb#33
  def service(new_service, constant_string); end

  # Returns service constant path, with provider, as string. If
  # "provider::service" is defined (the preferred format) then it returns that
  # string, otherwise it returns the deprecated string "service::provider".
  #
  # source://fog-core//lib/fog/core/provider.rb#47
  def service_klass(constant_string); end

  # source://fog-core//lib/fog/core/provider.rb#40
  def services; end

  class << self
    # @private
    #
    # source://fog-core//lib/fog/core/provider.rb#12
    def extended(base); end

    private

    # source://fog-core//lib/fog/core/provider.rb#20
    def underscore_name(string); end
  end
end

# source://fog-core//lib/fog/core/scp.rb#2
module Fog::SCP
  class << self
    # source://fog-core//lib/fog/core/scp.rb#3
    def new(address, username, options = T.unsafe(nil)); end
  end
end

# source://fog-core//lib/fog/core/scp.rb#11
class Fog::SCP::Mock
  # @return [Mock] a new instance of Mock
  #
  # source://fog-core//lib/fog/core/scp.rb#18
  def initialize(address, username, options); end

  # source://fog-core//lib/fog/core/scp.rb#34
  def download(remote_path, local_path, download_options = T.unsafe(nil)); end

  # source://fog-core//lib/fog/core/scp.rb#24
  def upload(local_path, remote_path, upload_options = T.unsafe(nil)); end

  class << self
    # source://fog-core//lib/fog/core/scp.rb#12
    def data; end
  end
end

# source://fog-core//lib/fog/core/scp.rb#45
class Fog::SCP::Real
  # @return [Real] a new instance of Real
  #
  # source://fog-core//lib/fog/core/scp.rb#46
  def initialize(address, username, options); end

  # source://fog-core//lib/fog/core/scp.rb#86
  def download(remote_path, local_path, download_options = T.unsafe(nil), &block); end

  # source://fog-core//lib/fog/core/scp.rb#76
  def upload(local_path, remote_path, upload_options = T.unsafe(nil), &block); end
end

# source://fog-core//lib/fog/core/ssh.rb#4
module Fog::SSH
  class << self
    # source://fog-core//lib/fog/core/ssh.rb#5
    def new(address, username, options = T.unsafe(nil)); end
  end
end

# source://fog-core//lib/fog/core/ssh.rb#13
class Fog::SSH::Mock
  # @return [Mock] a new instance of Mock
  #
  # source://fog-core//lib/fog/core/ssh.rb#24
  def initialize(address, username, options); end

  # source://fog-core//lib/fog/core/ssh.rb#30
  def run(commands, &_blk); end

  class << self
    # source://fog-core//lib/fog/core/ssh.rb#14
    def data; end

    # source://fog-core//lib/fog/core/ssh.rb#20
    def reset; end
  end
end

# source://fog-core//lib/fog/core/ssh.rb#35
class Fog::SSH::Real
  # @return [Real] a new instance of Real
  #
  # source://fog-core//lib/fog/core/ssh.rb#36
  def initialize(address, username, options); end

  # source://fog-core//lib/fog/core/ssh.rb#43
  def run(commands, &blk); end

  private

  # source://fog-core//lib/fog/core/ssh.rb#92
  def assert_net_ssh_loaded; end

  # Modifies the given `options` hash AND returns a new hash.
  # TODO: Probably shouldn't modify the given hash.
  #
  # source://fog-core//lib/fog/core/ssh.rb#103
  def build_options(options); end

  # source://fog-core//lib/fog/core/ssh.rb#108
  def merge_default_options_into(options); end

  # source://fog-core//lib/fog/core/ssh.rb#128
  def validate_options(options); end
end

# source://fog-core//lib/fog/core/ssh.rb#136
class Fog::SSH::Result
  # @return [Result] a new instance of Result
  #
  # source://fog-core//lib/fog/core/ssh.rb#152
  def initialize(command); end

  # Returns the value of attribute command.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def command; end

  # Sets the attribute command
  #
  # @param value the value to set the attribute command to.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def command=(_arg0); end

  # source://fog-core//lib/fog/core/ssh.rb#148
  def display_stderr; end

  # source://fog-core//lib/fog/core/ssh.rb#139
  def display_stdout; end

  # Returns the value of attribute status.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def status; end

  # Sets the attribute status
  #
  # @param value the value to set the attribute status to.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def status=(_arg0); end

  # Returns the value of attribute stderr.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def stderr; end

  # Sets the attribute stderr
  #
  # @param value the value to set the attribute stderr to.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def stderr=(_arg0); end

  # Returns the value of attribute stdout.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def stdout; end

  # Sets the attribute stdout
  #
  # @param value the value to set the attribute stdout to.
  #
  # source://fog-core//lib/fog/core/ssh.rb#137
  def stdout=(_arg0); end
end

# source://fog-core//lib/fog/core/service.rb#8
class Fog::Service
  class << self
    # source://fog-core//lib/fog/core/service.rb#161
    def coerce_options(options); end

    # source://fog-core//lib/fog/core/service.rb#148
    def collection(new_collection, path = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/service.rb#153
    def collection_files; end

    # source://fog-core//lib/fog/core/service.rb#157
    def collections; end

    # @deprecated
    #
    # source://fog-core//lib/fog/core/service.rb#120
    def fetch_credentials(_options); end

    # @private
    #
    # source://fog-core//lib/fog/core/service.rb#33
    def inherited(child); end

    # source://fog-core//lib/fog/core/service.rb#181
    def mocked_requests; end

    # source://fog-core//lib/fog/core/service.rb#185
    def model(new_model, path = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/service.rb#190
    def model_files; end

    # @note This path is used to require model and collection files
    #
    # source://fog-core//lib/fog/core/service.rb#144
    def model_path(new_path); end

    # source://fog-core//lib/fog/core/service.rb#194
    def models; end

    # {Fog::Service} is (unfortunately) both a builder class and the subclass for any fog service.
    #
    # Creating a {new} instance using the builder will return either an instance of
    # +Fog::<Service>::<Provider>::Real+ or +Fog::<Service>::<Provider>::Mock+ based on the value
    # of {Fog.mock?} when the builder is used.
    #
    # Each provider can require or recognize different settings (often prefixed with the providers
    # name). These settings map to keys in the +~/.fog+ file.
    #
    # Settings can be passed as either a Hash or an object that responds to +config_service?+ with
    # +true+. This object will be passed through unchanged to the +Real+ or +Mock+ service that is
    # created. It is up to providers to adapt services to use these config objects.
    #
    # @abstract Subclass and implement real or mock code
    # @example Configured using external config object (~/.fog ignored completely)
    #   @config = Fog::Example::Config.new(...)
    #   @service = Fog::Compute::Example.new(@config)
    # @example Configured using many options (options merged into ~/.fog)
    #   @options = {
    #   :example_username => "fog",
    #   :example_password => "fog"
    #   }
    #   @service = Fog::Compute::Example.new(@options)
    # @example Minimal options (dependent on ~/.fog)
    #   @service = Fog::Compute::Example.new # => <#Fog::Compute::Example::Real>
    # @example Mocked service
    #   Fog.mock!
    #   @service = Fog::Compute::Example.new # => <#Fog::Compute::Example::Mock>
    # @option config
    # @param config [Hash, #config_service?] Settings or an object used to build a service instance
    # @raise [ArgumentError] if a setting required by the provider was not passed in
    # @return [Fog::Service::Provider::Real] if created while mocking is disabled
    # @return [Fog::Service::Provider::Mock] if created while mocking is enabled
    #
    # source://fog-core//lib/fog/core/service.rb#94
    def new(config = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/service.rb#232
    def recognized; end

    # source://fog-core//lib/fog/core/service.rb#228
    def recognizes(*args); end

    # source://fog-core//lib/fog/core/service.rb#202
    def request(new_request, path = T.unsafe(nil)); end

    # source://fog-core//lib/fog/core/service.rb#198
    def request_path(new_path); end

    # source://fog-core//lib/fog/core/service.rb#206
    def requests; end

    # source://fog-core//lib/fog/core/service.rb#224
    def requirements; end

    # source://fog-core//lib/fog/core/service.rb#220
    def requires(*args); end

    # source://fog-core//lib/fog/core/service.rb#210
    def secrets(*args); end

    # source://fog-core//lib/fog/core/service.rb#128
    def setup_requirements; end

    # source://fog-core//lib/fog/core/service.rb#236
    def validate_options(options); end

    private

    # This converts names of collections from Symbols as defined in the DSL (+:database_server+)
    # into CamelCase version (+DatabaseServer+) for metaprogramming skulduggery.
    #
    # @param collection [String, Symbol] The name of the collection broken with underscores
    # @return [String] in camel case
    #
    # source://fog-core//lib/fog/core/service.rb#294
    def camel_case_collection_name(collection); end

    # This is the original way service settings were handled. Settings from +~/.fog+ were merged
    # together with the passed options, keys are turned to symbols and coerced into Boolean or
    # Fixnums.
    #
    # If the class has declared any required settings then {ArgumentError} will be raised.
    #
    # Any setting that is not whitelisted will cause a warning to be output.
    #
    # source://fog-core//lib/fog/core/service.rb#265
    def handle_settings(settings); end

    # source://fog-core//lib/fog/core/service.rb#277
    def require_collections_and_define; end

    # Requires the correct file for an item (collection, model, or request).
    #
    # @param fallback_dir [String] The directory to look for the file in if the first element of `item`
    #   is nil.
    # @param item [Array] An item to require. Should be an array in the form of [path, file].
    # @return [Boolean] Returns the same as `Kernel#require`.
    #
    # source://fog-core//lib/fog/core/service.rb#322
    def require_item(item, fallback_dir); end

    # This will attempt to require all model files declared by the service using fog"s DSL
    #
    # source://fog-core//lib/fog/core/service.rb#273
    def require_models; end

    # This will attempt to require all request files declared in the service using fog"s DSL
    #
    # source://fog-core//lib/fog/core/service.rb#299
    def require_requests_and_mock; end
  end
end

# source://fog-core//lib/fog/core/service.rb#18
module Fog::Service::Collections
  # source://fog-core//lib/fog/core/service.rb#19
  def collections; end

  # source://fog-core//lib/fog/core/service.rb#23
  def mocked_requests; end

  # source://fog-core//lib/fog/core/service.rb#27
  def requests; end
end

# source://fog-core//lib/fog/core/service.rb#9
class Fog::Service::Error < ::Fog::Errors::Error; end

# source://fog-core//lib/fog/core/service.rb#12
module Fog::Service::NoLeakInspector
  # source://fog-core//lib/fog/core/service.rb#13
  def inspect; end
end

# source://fog-core//lib/fog/core/service.rb#10
class Fog::Service::NotFound < ::Fog::Errors::NotFound; end

# source://fog-core//lib/fog/core/services_mixin.rb#2
module Fog::ServicesMixin
  # source://fog-core//lib/fog/core/services_mixin.rb#16
  def [](provider); end

  # source://fog-core//lib/fog/core/services_mixin.rb#20
  def new(attributes); end

  # source://fog-core//lib/fog/core/services_mixin.rb#37
  def providers; end

  private

  # source://fog-core//lib/fog/core/services_mixin.rb#75
  def check_provider_alias(provider); end

  # source://fog-core//lib/fog/core/services_mixin.rb#67
  def const_get_args(*args); end

  # This method should be removed once all providers are extracted.
  # Bundler will correctly require all dependencies automatically and thus
  # fog-core wont need to know any specifics providers. Each provider will
  # have to load its dependencies.
  #
  # source://fog-core//lib/fog/core/services_mixin.rb#47
  def require_service_provider_library(service, provider); end

  # source://fog-core//lib/fog/core/services_mixin.rb#71
  def service_name; end

  # source://fog-core//lib/fog/core/services_mixin.rb#57
  def service_provider_constant(service_name, provider_name); end
end

# source://fog-core//lib/fog/core/services_mixin.rb#3
Fog::ServicesMixin::E_SERVICE_PROVIDER_CONSTANT = T.let(T.unsafe(nil), String)

# source://fog-core//lib/fog/core/services_mixin.rb#9
Fog::ServicesMixin::E_SERVICE_PROVIDER_PATH = T.let(T.unsafe(nil), String)

# source://fog-core//lib/fog/storage.rb#9
module Fog::Storage
  extend ::Fog::ServicesMixin

  class << self
    # source://fog-core//lib/fog/storage.rb#12
    def directories; end

    # source://fog-core//lib/fog/storage.rb#23
    def get_body_size(body); end

    # source://fog-core//lib/fog/storage.rb#47
    def get_content_type(data); end

    # source://fog-core//lib/fog/storage.rb#56
    def parse_data(data); end
  end
end

class Fog::Storage::AWS < ::Fog::AWS::Storage; end
module Fog::Storage::AWS::Collections; end

# source://fog-core//lib/fog/core/stringify_keys.rb#2
module Fog::StringifyKeys
  class << self
    # Returns a new hash with all keys converted to strings.
    #
    # source://fog-core//lib/fog/core/stringify_keys.rb#4
    def stringify(original_hash); end

    # http://devblog.avdi.org/2009/11/20/hash-transforms-in-ruby/
    #
    # source://fog-core//lib/fog/core/stringify_keys.rb#11
    def transform_hash(original, &block); end
  end
end

# source://fog-core//lib/fog/support.rb#2
module Fog::Support
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/core/time.rb#4
class Fog::Time < ::Time
  # source://fog-core//lib/fog/core/time.rb#22
  def to_date_header; end

  # source://fog-core//lib/fog/core/time.rb#26
  def to_iso8601_basic; end

  class << self
    # source://fog-core//lib/fog/core/time.rb#8
    def now; end

    # source://fog-core//lib/fog/core/time.rb#12
    def now=(new_now); end

    # source://fog-core//lib/fog/core/time.rb#18
    def offset; end
  end
end

# source://fog-core//lib/fog/core/time.rb#5
Fog::Time::DAYS = T.let(T.unsafe(nil), Array)

# source://fog-core//lib/fog/core/time.rb#6
Fog::Time::MONTHS = T.let(T.unsafe(nil), Array)

# source://fog-core//lib/fog/core/uuid.rb#4
class Fog::UUID
  class << self
    # @return [Boolean]
    #
    # source://fog-core//lib/fog/core/uuid.rb#11
    def supported?; end

    # source://fog-core//lib/fog/core/uuid.rb#6
    def uuid; end
  end
end

# source://fog-core//lib/fog/vpn.rb#2
module Fog::VPN
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/volume.rb#2
module Fog::Volume
  extend ::Fog::ServicesMixin
end

# source://fog-core//lib/fog/core/whitelist_keys.rb#2
module Fog::WhitelistKeys
  class << self
    # source://fog-core//lib/fog/core/whitelist_keys.rb#3
    def whitelist(hash, valid_keys); end
  end
end
