# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `formatador` gem.
# Please instead update this file by running `bin/tapioca gem formatador`.


# source://formatador//lib/formatador/table.rb#1
class Formatador
  # @return [Formatador] a new instance of Formatador
  #
  # source://formatador//lib/formatador.rb#63
  def initialize; end

  # source://formatador//lib/formatador.rb#67
  def display(string = T.unsafe(nil)); end

  # source://formatador//lib/formatador/table.rb#10
  def display_compact_table(hashes, keys = T.unsafe(nil), **options, &block); end

  # source://formatador//lib/formatador.rb#73
  def display_line(string = T.unsafe(nil)); end

  # source://formatador//lib/formatador.rb#79
  def display_lines(lines = T.unsafe(nil)); end

  # source://formatador//lib/formatador/table.rb#2
  def display_table(hashes, keys = T.unsafe(nil), **options, &block); end

  # source://formatador//lib/formatador.rb#94
  def indent; end

  # source://formatador//lib/formatador.rb#101
  def indentation; end

  # source://formatador//lib/formatador.rb#117
  def new_line; end

  # source://formatador//lib/formatador.rb#86
  def parse(string); end

  # source://formatador//lib/formatador.rb#105
  def redisplay(string = T.unsafe(nil), width = T.unsafe(nil)); end

  # source://formatador//lib/formatador.rb#111
  def redisplay_line(string = T.unsafe(nil), width = T.unsafe(nil)); end

  # source://formatador//lib/formatador/progressbar.rb#34
  def redisplay_progressbar(current, total, options = T.unsafe(nil)); end

  # source://formatador//lib/formatador.rb#122
  def set_title(title); end

  # source://formatador//lib/formatador.rb#128
  def strip(string); end

  private

  # source://formatador//lib/formatador/table.rb#89
  def calculate_datum(header, hash); end

  # source://formatador//lib/formatador.rb#152
  def color_support; end

  # source://formatador//lib/formatador/table.rb#82
  def length(value); end

  # source://formatador//lib/formatador/progressbar.rb#50
  def progressbar(current, total, options); end

  class << self
    def display(*args, &block); end
    def display_compact_table(*args, **kwargs, &block); end
    def display_line(*args, &block); end
    def display_lines(*args, &block); end
    def display_table(*args, **kwargs, &block); end
    def indent(*args, &block); end
    def new_line(*args, &block); end
    def parse(*args, &block); end
    def redisplay(*args, &block); end
    def redisplay_line(*args, &block); end
    def redisplay_progressbar(*args, &block); end
    def set_title(*args, &block); end
  end
end

# source://formatador//lib/formatador.rb#61
Formatador::INDENT_REGEX = T.let(T.unsafe(nil), Regexp)

# source://formatador//lib/formatador.rb#60
Formatador::PARSE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://formatador//lib/formatador/progressbar.rb#5
class Formatador::ProgressBar
  # @return [ProgressBar] a new instance of ProgressBar
  #
  # source://formatador//lib/formatador/progressbar.rb#9
  def initialize(total, opts = T.unsafe(nil), &block); end

  # Returns the value of attribute current.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def current; end

  # Sets the attribute current
  #
  # @param value the value to set the attribute current to.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def current=(_arg0); end

  # source://formatador//lib/formatador/progressbar.rb#17
  def increment(increment = T.unsafe(nil)); end

  # Returns the value of attribute opts.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def opts; end

  # Sets the attribute opts
  #
  # @param value the value to set the attribute opts to.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def opts=(_arg0); end

  # Returns the value of attribute total.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def total; end

  # Sets the attribute total
  #
  # @param value the value to set the attribute total to.
  #
  # source://formatador//lib/formatador/progressbar.rb#7
  def total=(_arg0); end

  private

  # @return [Boolean]
  #
  # source://formatador//lib/formatador/progressbar.rb#28
  def complete?; end
end

# source://formatador//lib/formatador.rb#11
Formatador::STYLES = T.let(T.unsafe(nil), Hash)

# source://formatador//lib/formatador.rb#9
Formatador::VERSION = T.let(T.unsafe(nil), String)
