export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';

export const FETCH_CABINS_START = 'FETCH_CABINS_START';
export const FETCH_CABINS = 'FETCH_CABINS';
export const FETCH_CABINS_SUCCESS = 'FETCH_CABINS_SUCCESS';
export const FETCH_CABINS_FAIL = 'FETCH_CABINS_FAIL';
export const CREATE_CABIN = 'CREATE_CABIN';
export const DELETE_CABIN = 'DELETE_CABIN';
export const EDIT_CABIN = 'EDIT_CABIN';

export const FETCH_EVENTS_START = 'FETCH_EVENTS_START'; 
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const FETCH_PICTURES_START = 'FETCH_PICTURES_START';
export const FETCH_PICTURES = 'FETCH_PICTURES';
export const FETCH_PICTURES_SUCCESS = 'FETCH_PICTURES_SUCCESS';
export const FETCH_PICTURES_FAIL = 'FETCH_PICTURES_FAIL';
export const CREATE_PICTURE = 'CREATE_PICTURE';
export const DELETE_PICTURE = 'DELETE_PICTURE';

export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';