export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL'
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDIT_ARTICLE_FAIL = 'EDIT_ARTICLE_FAIL';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';

export const FETCH_CABINS = 'FETCH_CABINS';
export const FETCH_CABINS_SUCCESS = 'FETCH_CABINS_SUCCESS';
export const FETCH_CABINS_FAIL = 'FETCH_CABINS_FAIL';
export const CREATE_CABIN = 'CREATE_CABIN';
export const CREATE_CABIN_SUCCESS = 'CREATE_CABIN_SUCCESS';
export const CREATE_CABIN_FAIL = 'CREATE_CABIN_FAIL'
export const EDIT_CABIN = 'EDIT_CABIN';
export const EDIT_CABIN_FAIL = 'EDIT_CABIN_FAIL';
export const EDIT_CABIN_SUCCESS = 'EDIT_CABIN_SUCCESS';
export const DELETE_CABIN = 'DELETE_CABIN';
export const DELETE_CABIN_SUCCESS = 'DELETE_CABIN_SUCCESS';
export const DELETE_CABIN_FAIL = 'DELETE_CABIN_FAIL';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL'
export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

export const FETCH_PICTURES = 'FETCH_PICTURES';
export const FETCH_PICTURES_SUCCESS = 'FETCH_PICTURES_SUCCESS';
export const FETCH_PICTURES_FAIL = 'FETCH_PICTURES_FAIL';
export const CREATE_PICTURE = 'CREATE_PICTURE';
export const CREATE_PICTURE_SUCCESS = 'CREATE_PICTURE_SUCCESS';
export const CREATE_PICTURE_FAIL = 'CREATE_PICTURE_FAIL'
export const DELETE_PICTURE = 'DELETE_PICTURE';
export const DELETE_PICTURE_SUCCESS = 'DELETE_PICTURE_SUCCESS';
export const DELETE_PICTURE_FAIL = 'DELETE_PICTURE_FAIL';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const CHECK_AUTH_STATE_SUCCESS = 'CHECK_AUTH_STATE_SUCCESS';
export const CHECK_AUTH_STATE_FAIL = 'CHECK_AUTH_STATE_FAIL';

export const SEARCH = 'SEARCH'
export const SEARCH_LOADING = 'SEARCH_LOADING'
export const SEARCH_COMPLETE = 'SEARCH_COMPLETE'

export const ADD_CABIN_IMAGE = 'ADD_CABIN_IMAGE';
export const ADD_CABIN_IMAGE_SUCCESS = 'ADD_CABIN_IMAGE_SUCCESS';
export const ADD_CABIN_IMAGE_FAIL = 'ADD_CABIN_IMAGE_FAIL';
export const DELETE_CABIN_IMAGE_FAIL = 'DELETE_CABIN_IMAGE_FAIL';
export const DELETE_CABIN_IMAGE = 'DELETE_CABIN_IMAGE';
export const DELETE_CABIN_IMAGE_SUCCESS = 'DELETE_CABIN_IMAGE_SUCCESS';
export const FETCH_CABIN_IMAGES = 'FETCH_CABIN_IMAGES'
export const FETCH_CABIN_IMAGES_SUCCESS = 'FETCH_CABIN_IMAGES_SUCCESS';
export const FETCH_CABIN_IMAGES_FAIL = 'FETCH_CABIN_IMAGES_FAIL';