# typed: true

# Hand-written shims for ActiveRecord column accessors and dynamic methods
# that would normally be generated by `tapioca dsl` (requires DB connection).

class User
  sig { returns(T.nilable(String)) }
  def email; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def email=(value); end

  sig { returns(T.nilable(String)) }
  def remember_digest; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def remember_digest=(value); end

  sig { returns(T.nilable(T::Boolean)) }
  def email_confirmed; end

  sig { params(value: T.nilable(T::Boolean)).returns(T.nilable(T::Boolean)) }
  def email_confirmed=(value); end

  sig { returns(T.nilable(String)) }
  def confirm_token; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def confirm_token=(value); end

  sig { returns(T.nilable(ActiveSupport::TimeWithZone)) }
  def password_reset_sent_at; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def password_reset_sent_at=(value); end

  sig { returns(T.nilable(String)) }
  def password_reset_token; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def password_reset_token=(value); end
end

class Event
  sig { returns(T.untyped) }
  def start_time; end

  sig { returns(T.untyped) }
  def end_time; end
end

class Cabindate
  sig { returns(T.untyped) }
  def startdate; end

  sig { returns(T.untyped) }
  def enddate; end
end

class Comment
  sig { returns(T.untyped) }
  def user; end
end
