# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '3.2.2'

gem 'active_model_serializers'
gem 'aws-sdk-s3', require: false
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'fog-aws', group: :production
gem 'friendly_id', '~> 5.2.4'
gem 'jbuilder', '~> 2.5'
gem 'jwt'
gem 'open-weather'
gem 'pg'
gem 'psych', '< 4'
gem 'puma', '~> 3.11'
gem 'rack-cors'
gem 'rails', '~> 6.1.3.2'
gem 'rails-controller-testing'
gem 'redis', '~> 4.0'
gem 'rswag-api'
gem 'rswag-ui'
gem 'rubocop'
gem 'sassc-rails'
gem 'will_paginate'
# Use ActiveStorage variant
gem 'mini_magick', '~> 4.8'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'lograge', '~> 0.14.0'
gem 'prometheus-client'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
  gem 'rswag-specs'
end

group :development do
  gem 'solargraph'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'better_errors'
  gem 'guard'
  gem 'guard-livereload', '~> 2.5', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
end
