# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '3.2.2'

gem 'active_model_serializers'
gem 'aws-sdk-s3', require: false
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'fog-aws', group: :production
gem 'friendly_id', '~> 5.5'
gem 'heroicon'
gem 'importmap-rails'
gem 'lexxy', '~> 0.1.26.beta'
gem 'jbuilder'
gem 'json', '>= 2.6'
gem 'jwt'
gem 'lograge'
gem 'mini_magick', '~> 4.8'
gem 'open-weather'
gem 'pg'
gem 'prism', '~> 1.3.0'
gem 'propshaft'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'rails', '~> 8.0.2'
gem 'redis', '~> 5.0'
gem 'rollbar'
gem 'rubocop'
gem 'sorbet-runtime'
gem 'stimulus-rails'
gem 'tailwindcss-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'view_component'
gem 'will_paginate'

group :development, :test do
  gem 'annotate'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'faker'
  gem 'herb'
  gem 'rspec-rails'
  gem 'rswag-specs'
  gem 'tapioca', '>= 0.17.10', require: false
end

group :development do
  gem 'listen'
  gem 'ruby-lsp'
  gem 'sorbet'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'factory_bot_rails'
  gem 'shoulda-matchers'
end
