name: Deploy to Production

on:
  push:
    branches: [ new-frontend ]

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Staging WWW Image'
        run: |
          touch frontend/.env.staging;
          echo "PUBLIC_API_URL=https://caqqdrrb6ke2g9yrmeauhbkhg.diehlsillers.xyz/api" >> frontend/.env.production;
          echo "PUBLIC_BASE_URL=https://caqqdrrb6ke2g9yrmeauhbkhg.diehlsillers.xyz" >> frontend/.env.production;
          echo "PUBLIC_INSEASON_RESERVATION_LINK=${{ vars.PUBLIC_INSEASON_RESERVATION_LINK }}" >> frontend/.env.production;
          echo "PUBLIC_OUTSEASON_RESERVATION_LINK=${{ vars.PUBLIC_OUTSEASON_RESERVATION_LINK }}" >> frontend/.env.production;
          echo "PUBLIC_VERSION=${{ github.sha }}" >> frontend/.env.staging;
          echo "PUBLIC_ENVIRONMENT=staging" >> frontend/.env.staging;
          echo "PUBLIC_UPLOADS_S3_BUCKET=ironcityfishingclub" >> frontend/.env.staging;
          docker build . -f Dockerfile.api --tag ghcr.io/diehlms/icfc-api-staging:${{ github.sha }}
          docker build . -f Dockerfile.www --build-arg ENVIRONMENT_FILE=".env.staging" --tag ghcr.io/diehlms/icfc-www-staging:${{ github.sha }}
          docker push ghcr.io/diehlms/icfc-api-staging:${{ github.sha }}
          docker push ghcr.io/diehlms/icfc-www-staging:${{ github.sha }}

      - name: 'Build Production WWW Image'
        run: |
          touch frontend/.env.production;
          echo "PUBLIC_API_URL=https://icfc.net/api" >> frontend/.env.production;
          echo "PUBLIC_BASE_URL=https://icfc.net" >> frontend/.env.production;
          echo "PUBLIC_INSEASON_RESERVATION_LINK=${{ vars.PUBLIC_INSEASON_RESERVATION_LINK }}" >> frontend/.env.production;
          echo "PUBLIC_OUTSEASON_RESERVATION_LINK=${{ vars.PUBLIC_OUTSEASON_RESERVATION_LINK }}" >> frontend/.env.production;
          echo "PUBLIC_VERSION=${{ github.sha }}" >> frontend/.env.production;
          echo "PUBLIC_ENVIRONMENT=production" >> frontend/.env.production;
          echo "PUBLIC_UPLOADS_S3_BUCKET=ironcityfishingclub" >> frontend/.env.production;
          docker build . -f Dockerfile.api --tag ghcr.io/diehlms/icfc-api:${{ github.sha }}
          docker build . -f Dockerfile.www --tag ghcr.io/diehlms/icfc-www:${{ github.sha }}
          docker push ghcr.io/diehlms/icfc-api:${{ github.sha }}
          docker push ghcr.io/diehlms/icfc-www:${{ github.sha }}

  deploy:
    runs-on: [self-hosted, linux, X64]
    needs: [publish]
    steps:
      - uses: actions/checkout@v2

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      # TODO: make next two steps manually triggered for prod deploys
      - name: Update Docker Compose File with Image
        run: |
          export API_IMAGE="ghcr.io/diehlms/icfc-api:${{ github.sha }}";
          export WWW_IMAGE="ghcr.io/diehlms/icfc-www:${{ github.sha }}";
          yq eval ".services.web.image = \"$API_IMAGE\"" -i docker-compose-staging.yml
          yq eval ".services.nginx.image = \"$WWW_IMAGE\"" -i docker-compose-staging.yml
          yq eval ".services.web.image = \"$API_IMAGE\"" -i docker-compose-production.yml
          yq eval ".services.nginx.image = \"$WWW_IMAGE\"" -i docker-compose-production.yml

      - name: Deploy to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          scp -i ~/.ssh/deploy_key proxy/nginx.staging.conf $DEPLOY_USER@$DEPLOY_HOST:~/app/proxy/nginx.staging.conf
          scp -i ~/.ssh/deploy_key proxy/nginx.prod.conf $DEPLOY_USER@$DEPLOY_HOST:~/app/proxy/nginx.prod.conf
          scp -i ~/.ssh/deploy_key docker-compose-staging.yml $DEPLOY_USER@$DEPLOY_HOST:~/app/docker-compose-staging.yml
          scp -i ~/.ssh/deploy_key docker-compose-production.yml $DEPLOY_USER@$DEPLOY_HOST:~/app/docker-compose-production.yml
          
          echo "Deploying staging..."

          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST '\
            cd ~/app && \
            docker compose -f docker-compose-staging.yml pull && \
            docker compose -f docker-compose-staging.yml up -d'

          echo "Deploying production..."

          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST '\
            cd ~/app && \
            docker compose -f docker-compose-production.yml pull && \
            docker compose -f docker-compose-production.yml up -d'
